name: GitHub Metrics

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "15 18,6 * * *"   # midnight + noon Nepal time

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SuhanVerse
          template: classic
          config_timezone: Asia/Kathmandu
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: SuhanVerse, khsuhan100@gmail.com
          filename: |
            metrics/overview.svg
            metrics/habits.svg
            metrics/calendar.svg
          base: header, activity, community, repositories, metadata

          # Habits plugin
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
