name: GitHub Metrics

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # daily at midnight UTC

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SuhanVerse
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu

          # Hide less relevant stats
          config_hide: issues, prs, followers, stars, forks

          # --- Plugins for richer stats ---
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_from: 200   # analyze last 200 commits
          plugin_habits_days: 14    # over the last 2 weeks
          plugin_habits_facts: yes  # show fun facts

          plugin_repositories: yes
          plugin_repositories_featured: SuhanVerse/Learning-ROS2, SuhanVerse/SuhanVerse
