name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SuhanVerse
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kathmandu
