name: PACMAN GAME

on:
  schedule:
    - cron: "15 18,6 * * *"   # midnight + noon Nepal time
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man Graph (Light)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
      - run: |
          mkdir -p Pacman
          mv dist/pacman-contribution-graph.svg Pacman/pacman-contribution-graph.svg

      - name: Generate Pac-Man Graph (Dark)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: dark
      - run: |
          mv dist/pacman-contribution-graph.svg Pacman/pacman-contribution-graph-dark.svg

      - name: Commit and push to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Pacman/pacman-contribution-graph*.svg
          git commit -m "Update Pac-Man contribution graphs [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
